export const GET_ALL_COUPLES_LOADING = 'GET_ALL_COUPLES_LOADING';
export const GET_ALL_COUPLES_ERROR = 'GET_ALL_COUPLES_ERROR';
export const GET_ALL_COUPLES_SUCCESS = 'GET_ALL_COUPLES_SUCCESS';
export const UPDATE_COUPLE_LOADING = 'UPDATE_COUPLE_LOADING';
export const UPDATE_COUPLE_ERROR = 'UPDATE_COUPLES_ERROR';
export const UPDATE_COUPLE_SUCCESS = 'UPDATE_COUPLES_SUCCESS';
